name: Backend Continuous Integration

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NOTIFICATIONS_PUSH_ENABLED: false
      FIREBASE_PROJECT_ID: restock-10253
      FIREBASE_SERVICE_ACCOUNT_BASE64: test-disabled

    steps:
      - name: 1. Checkout del codigo
        uses: actions/checkout@v4

      - name: 2. Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: 3. Ejecutar Pruebas
        run: mvn test

      - name: 4. Empaquetar
        run: mvn clean package -DskipTests
